distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools 35.0.0
        run: sdkmanager "build-tools;35.0.0"

      - name: Verify installed SDK Packages
        run: sdkmanager --list

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.9"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "ubuntulinux-ci"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
          link-to-sdk: true

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Debug and Unsigned Release APKs
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Unsigned Release APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-release-unsigned-apk
          path: app/build/outputs/apk/release/*-unsigned.apk

      - name: Sign Release APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: kevin-david/zipalign-sign-android-release@v2
        id: sign_app
